// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAev3O2VEOTnJ7D2M0TRIpp-a3n-2G0tg',
    appId: '1:138743974989:web:991310dd6cd0d97609e004',
    messagingSenderId: '138743974989',
    projectId: 'muscat-car-wash0-8b907',
    authDomain: 'muscat-car-wash0-8b907.firebaseapp.com',
    storageBucket: 'muscat-car-wash0-8b907.appspot.com',
    measurementId: 'G-H44PCNXL1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNliysN8mWFo5KgwnNnEM9vMZEGDgquuY',
    appId: '1:138743974989:android:1d2810ea7605ecfa09e004',
    messagingSenderId: '138743974989',
    projectId: 'muscat-car-wash0-8b907',
    storageBucket: 'muscat-car-wash0-8b907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2EibisvkRWDkcvmYNGRHQCKCHcXMYBDU',
    appId: '1:138743974989:ios:3fdf1dc625b2301209e004',
    messagingSenderId: '138743974989',
    projectId: 'muscat-car-wash0-8b907',
    storageBucket: 'muscat-car-wash0-8b907.appspot.com',
    iosBundleId: 'com.example.muscatCarWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2EibisvkRWDkcvmYNGRHQCKCHcXMYBDU',
    appId: '1:138743974989:ios:3fdf1dc625b2301209e004',
    messagingSenderId: '138743974989',
    projectId: 'muscat-car-wash0-8b907',
    storageBucket: 'muscat-car-wash0-8b907.appspot.com',
    iosBundleId: 'com.example.muscatCarWash',
  );
}
